name: RailSathi Deployment

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            
            - name: set up node.js
              uses: actions/setup-node@v4
              with:
                node-version: 24
               
    